name: Deploy to App 1
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy formsflow
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.APP1_HOST }}
        username: ${{ secrets.APP1_USERNAME }}
        key: ${{ secrets.APP1_KEY }}
        passphrase: ${{ secrets.APP1_PASSPHRASE }}
        script: |
          cd /home/dev/apps/forms-flow-ai/deployment/docker
          docker compose down
          cd /home/dev/apps/forms-flow-ai
          git stash
          git pull origin develop
          git stash apply
          cd /home/dev/apps/forms-flow-ai/deployment/docker
          docker compose up --build -d
          cd /home/dev/apps/admin
          docker compose down
          docker compose up -d
