name: Deploy to App 1
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy formsflow
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.APP1_HOST }}
        username: ${{ secrets.APP1_USERNAME }}
        key: ${{ secrets.APP1_KEY }}
        passphrase: ${{ secrets.APP1_PASSPHRASE }}
        script: |
          ls -lsa
          whoami
          
          
